version: "3.8"
services:
#nginx reverse proxy qui contient le front
  nginx:
    container_name: nginx
    image: front
    depends_on:
      - api
    build:
      context: ./front/
      dockerfile: ./front/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#api quarkus
  api:
    container_name: api
    image: quarkus/code-with-quarkus-fast-jar:latest
    depends_on:
      - db
      - mail
      - etherpad
    build:
      context: ./api/
      dockerfile: ./api/src/main/docker/Dockerfile.fast-jar
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://db:3306/tlc?useUnicode=true&serverTimezone=Europe/Paris
      - doodle.internalPadUrl=http://etherpad:9001/
      #- doodle.externalPadUrl=http://etherpad.tlc.fr:8090/
    ports:
      - 8080:8080
#phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
#mysql
  db:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
    #chercher le scipt sql d'initialisation
    #volumes:
    #  - ./api/src/main/resources/db/migration:/docker-entrypoint-initdb.d
    #command: [
    #  '--init-file=/docker-entrypoint-initdb.d/V1__Initial_version.sql'
    #]
#mail
  mail:
    container_name: mail
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
#etherpad
  etherpad:
    container_name: etherpad
    image: etherpad/etherpad:latest
    ports:
      - "9001:9001"
    volumes:
      - ./api/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt 